/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.201.0Release
// Tag = production/release/21.201.0-0-g39a0a60c
/////////////////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit.csv;

import java.io.BufferedWriter;
import java.io.ByteArrayOutputStream;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;

class CSVWriterPrefixable implements CSVWritable {
    private final ByteArrayOutputStream outputStream;
    private BufferedWriter writer;

    public CSVWriterPrefixable(ByteArrayOutputStream outputStream) {
        this.outputStream = outputStream;
    }

    @Override
    public void close(ArrayList<String> headers) {
        try {
            if (writer != null) {
                StringBuilder headerStringBuilder = new StringBuilder(); 
                for (String header : headers) {
                    headerStringBuilder.append(header + ",");
                }
                headerStringBuilder.append("\n");

                OutputStream headerStream = new ByteArrayOutputStream();
                headerStream.write(headerStringBuilder.toString().getBytes(StandardCharsets.UTF_8));

                if (outputStream instanceof PrefixableByteArrayOutputStream) {
                    ((PrefixableByteArrayOutputStream) outputStream).setPrefixStream((ByteArrayOutputStream) headerStream);
                }

                writer.close();
                writer = null;
            }
        } catch (java.io.IOException e) {
            throw new RuntimeException(e);
        }
    }

    @Override
    public void writeln(ArrayList<String> values, int maxNumberValues) {
        try {
            if (writer == null) {
                writer = new BufferedWriter(new OutputStreamWriter(outputStream, StandardCharsets.UTF_8));
            }

            for (String value : values) {
                writer.write(value + ",");
            }

            if (values.size() < maxNumberValues) {
                for (int i = 0; i < maxNumberValues - values.size(); i++) {
                    writer.write(",");
                }
            }

            writer.write("\n");
        } catch (java.io.IOException e) {
            throw new RuntimeException(e);
        }
    }
}
