/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.202.0Release
// Tag = production/release/21.202.0-0-g9a57aebc
/////////////////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit.csv;

import java.io.ByteArrayOutputStream;
import java.util.ArrayList;
import java.util.Collections;


public class CSVWriter {
    CSVWritable csvWriter;
    private final ArrayList<String> headers = new ArrayList<>();
    private final ArrayList<String> values = new ArrayList<>();
    private int maxNumberValues = 0;

    public CSVWriter(ByteArrayOutputStream outputStream) {
        csvWriter = (outputStream instanceof ByteArrayOutputStreamPrefixable) ? new CSVWriterPrefixable(outputStream) : new CSVWriterBufferedOutput(outputStream);
    }

    public ArrayList<String> getHeaders(){
        return headers;
    }

    public void close() {
        csvWriter.close(headers);
    }

    public void writeln() {
        csvWriter.writeln(values, maxNumberValues);
    }

    public void clear() {
        Collections.fill(values, "");
    }

    public void set(String header, Object value) {
        if (header == null) {
            header = "null";
        }

        if (value == null) {
            value = "null";
        }

        for (int i = 0; i < headers.size(); i++) {
            if (headers.get(i).compareTo(header) == 0) {
                values.set(i, value.toString());
                return;
            }
        }

        headers.add(header);
        values.add(value.toString());
    }

    public void setMaxNumberValues(int numberValues) {
        maxNumberValues = numberValues;
    }
}