/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;




public class BatteryMesg extends Mesg   {

    
    public static final int TimestampFieldNum = 253;
    
    public static final int CapacityFieldNum = 2;
    

    protected static final  Mesg batteryMesg;
    static {
        // battery
        batteryMesg = new Mesg("battery", MesgNum.BATTERY);
        batteryMesg.addField(new Field("timestamp", TimestampFieldNum, 134, 1, 0, "", false, Profile.Type.DATE_TIME));
        
        batteryMesg.addField(new Field("capacity", CapacityFieldNum, 2, 1, 0, "%", false, Profile.Type.UINT8));
        
    }

    public BatteryMesg() {
        super(Factory.createMesg(MesgNum.BATTERY));
    }

    public BatteryMesg(final Mesg mesg) {
        super(mesg);
    }


    /**
     * Get timestamp field
     *
     * @return timestamp
     */
    public DateTime getTimestamp() {
        return timestampToDateTime(getFieldLongValue(253, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD));
    }

    /**
     * Set timestamp field
     *
     * @param timestamp The new timestamp value to be set
     */
    public void setTimestamp(DateTime timestamp) {
        setFieldValue(253, 0, timestamp.getTimestamp(), Fit.SUBFIELD_INDEX_MAIN_FIELD);
    }

    /**
     * Get capacity field
     * Units: %
     *
     * @return capacity
     */
    public Short getCapacity() {
        return getFieldShortValue(2, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD);
    }

    /**
     * Set capacity field
     * Units: %
     *
     * @param capacity The new capacity value to be set
     */
    public void setCapacity(Short capacity) {
        setFieldValue(2, 0, capacity, Fit.SUBFIELD_INDEX_MAIN_FIELD);
    }

}
