/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;



public enum BritishTechnicalGradingScale  {
    _1((short)0),
    _2((short)1),
    _3((short)2),
    _4A((short)3),
    _4B((short)4),
    _4C((short)5),
    _5A((short)6),
    _5B((short)7),
    _5C((short)8),
    _6A((short)9),
    _6B((short)10),
    _6C((short)11),
    _7A((short)12),
    _7B((short)13),
    _7C((short)14),
    INVALID((short)255);

    protected short value;

    private BritishTechnicalGradingScale(short value) {
        this.value = value;
    }

    public static BritishTechnicalGradingScale getByValue(final Short value) {
        for (final BritishTechnicalGradingScale type : BritishTechnicalGradingScale.values()) {
            if (value == type.value)
                return type;
        }

        return BritishTechnicalGradingScale.INVALID;
    }

    /**
     * Retrieves the String Representation of the Value
     * @param value The enum constant
     * @return The name of this enum constant
     */
    public static String getStringFromValue( BritishTechnicalGradingScale value ) {
        return value.name();
    }

    public short getValue() {
        return value;
    }


}
