/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;



public enum ClimbGradingScale  {
    YDS((short)0),
    UIAA((short)1),
    FRENCH((short)2),
    BRITISH_ADJECTIVAL((short)3),
    BRITISH_TECHNICAL((short)4),
    EWBANK((short)5),
    BRAZILIAN((short)6),
    SAXON((short)7),
    VERMIN((short)8),
    FONT((short)9),
    DANKYU((short)10),
    YDS_PM((short)11),
    INVALID((short)255);

    protected short value;

    private ClimbGradingScale(short value) {
        this.value = value;
    }

    public static ClimbGradingScale getByValue(final Short value) {
        for (final ClimbGradingScale type : ClimbGradingScale.values()) {
            if (value == type.value)
                return type;
        }

        return ClimbGradingScale.INVALID;
    }

    /**
     * Retrieves the String Representation of the Value
     * @param value The enum constant
     * @return The name of this enum constant
     */
    public static String getStringFromValue( ClimbGradingScale value ) {
        return value.name();
    }

    public short getValue() {
        return value;
    }


}
