/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;



public enum FontGradingScale  {
    _1((short)0),
    _2((short)1),
    _3((short)2),
    _4((short)3),
    _4_PLUS((short)4),
    _5((short)5),
    _5_PLUS((short)6),
    _6A((short)7),
    _6A_PLUS((short)8),
    _6B((short)9),
    _6B_PLUS((short)10),
    _6C((short)11),
    _6C_PLUS((short)12),
    _7A((short)13),
    _7A_PLUS((short)14),
    _7B((short)15),
    _7B_PLUS((short)16),
    _7C((short)17),
    _7C_PLUS((short)18),
    _8A((short)19),
    _8A_PLUS((short)20),
    _8B((short)21),
    _8B_PLUS((short)22),
    _8C((short)23),
    _8C_PLUS((short)24),
    _9A((short)25),
    INVALID((short)255);

    protected short value;

    private FontGradingScale(short value) {
        this.value = value;
    }

    public static FontGradingScale getByValue(final Short value) {
        for (final FontGradingScale type : FontGradingScale.values()) {
            if (value == type.value)
                return type;
        }

        return FontGradingScale.INVALID;
    }

    /**
     * Retrieves the String Representation of the Value
     * @param value The enum constant
     * @return The name of this enum constant
     */
    public static String getStringFromValue( FontGradingScale value ) {
        return value.name();
    }

    public short getValue() {
        return value;
    }


}
