/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.202.0Release
// Tag = production/release/21.202.0-0-g9a57aebc
/////////////////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;



public enum NapSource  {
    AUTOMATIC((short)0),
    MANUAL_DEVICE((short)1),
    MANUAL_GC((short)2),
    INVALID((short)255);

    protected short value;

    private NapSource(short value) {
        this.value = value;
    }

    public static NapSource getByValue(final Short value) {
        for (final NapSource type : NapSource.values()) {
            if (value == type.value)
                return type;
        }

        return NapSource.INVALID;
    }

    /**
     * Retrieves the String Representation of the Value
     * @param value The enum constant
     * @return The name of this enum constant
     */
    public static String getStringFromValue( NapSource value ) {
        return value.name();
    }

    public short getValue() {
        return value;
    }


}
