/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;



public enum SaxonGradingScale  {
    I((short)0),
    II((short)1),
    III((short)2),
    IV((short)3),
    V((short)4),
    VI((short)5),
    VII_A((short)6),
    VII_B((short)7),
    VII_C((short)8),
    VIII_A((short)9),
    VIII_B((short)10),
    VIII_C((short)11),
    IX_A((short)12),
    IX_B((short)13),
    IX_C((short)14),
    X_A((short)15),
    X_B((short)16),
    X_C((short)17),
    XI_A((short)18),
    XI_B((short)19),
    XI_C((short)20),
    XII_A((short)21),
    XII_B((short)22),
    XII_C((short)23),
    INVALID((short)255);

    protected short value;

    private SaxonGradingScale(short value) {
        this.value = value;
    }

    public static SaxonGradingScale getByValue(final Short value) {
        for (final SaxonGradingScale type : SaxonGradingScale.values()) {
            if (value == type.value)
                return type;
        }

        return SaxonGradingScale.INVALID;
    }

    /**
     * Retrieves the String Representation of the Value
     * @param value The enum constant
     * @return The name of this enum constant
     */
    public static String getStringFromValue( SaxonGradingScale value ) {
        return value.name();
    }

    public short getValue() {
        return value;
    }


}
