/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.195.0Release
// Tag = production/release/21.195.0-0-g569e7e5
/////////////////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;




public class SleepDisruptionOvernightSeverityMesg extends Mesg   {

    
    public static final int TimestampFieldNum = 253;
    
    public static final int SeverityFieldNum = 0;
    

    protected static final  Mesg sleepDisruptionOvernightSeverityMesg;
    static {
        // sleep_disruption_overnight_severity
        sleepDisruptionOvernightSeverityMesg = new Mesg("sleep_disruption_overnight_severity", MesgNum.SLEEP_DISRUPTION_OVERNIGHT_SEVERITY);
        sleepDisruptionOvernightSeverityMesg.addField(new Field("timestamp", TimestampFieldNum, 134, 1, 0, "", false, Profile.Type.DATE_TIME));
        
        sleepDisruptionOvernightSeverityMesg.addField(new Field("severity", SeverityFieldNum, 0, 1, 0, "", false, Profile.Type.SLEEP_DISRUPTION_SEVERITY));
        
    }

    public SleepDisruptionOvernightSeverityMesg() {
        super(Factory.createMesg(MesgNum.SLEEP_DISRUPTION_OVERNIGHT_SEVERITY));
    }

    public SleepDisruptionOvernightSeverityMesg(final Mesg mesg) {
        super(mesg);
    }


    /**
     * Get timestamp field
     *
     * @return timestamp
     */
    public DateTime getTimestamp() {
        return timestampToDateTime(getFieldLongValue(253, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD));
    }

    /**
     * Set timestamp field
     *
     * @param timestamp The new timestamp value to be set
     */
    public void setTimestamp(DateTime timestamp) {
        setFieldValue(253, 0, timestamp.getTimestamp(), Fit.SUBFIELD_INDEX_MAIN_FIELD);
    }

    /**
     * Get severity field
     *
     * @return severity
     */
    public SleepDisruptionSeverity getSeverity() {
        Short value = getFieldShortValue(0, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD);
        if (value == null) {
            return null;
        }
        return SleepDisruptionSeverity.getByValue(value);
    }

    /**
     * Set severity field
     *
     * @param severity The new severity value to be set
     */
    public void setSeverity(SleepDisruptionSeverity severity) {
        setFieldValue(0, 0, severity.value, Fit.SUBFIELD_INDEX_MAIN_FIELD);
    }

}
