/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;



public enum UiaaGradingScale  {
    I((short)0),
    II((short)1),
    III((short)2),
    IV_MINUS((short)3),
    IV((short)4),
    IV_PLUS((short)5),
    V_MINUS((short)6),
    V((short)7),
    V_PLUS((short)8),
    VI_MINUS((short)9),
    VI((short)10),
    VI_PLUS((short)11),
    VII_MINUS((short)12),
    VII((short)13),
    VII_PLUS((short)14),
    VIII_MINUS((short)15),
    VIII((short)16),
    VIII_PLUS((short)17),
    IX_MINUS((short)18),
    IX((short)19),
    IX_PLUS((short)20),
    X_MINUS((short)21),
    X((short)22),
    X_PLUS((short)23),
    XI_MINUS((short)24),
    XI((short)25),
    XI_PLUS((short)26),
    XII_MINUS((short)27),
    INVALID((short)255);

    protected short value;

    private UiaaGradingScale(short value) {
        this.value = value;
    }

    public static UiaaGradingScale getByValue(final Short value) {
        for (final UiaaGradingScale type : UiaaGradingScale.values()) {
            if (value == type.value)
                return type;
        }

        return UiaaGradingScale.INVALID;
    }

    /**
     * Retrieves the String Representation of the Value
     * @param value The enum constant
     * @return The name of this enum constant
     */
    public static String getStringFromValue( UiaaGradingScale value ) {
        return value.name();
    }

    public short getValue() {
        return value;
    }


}
