/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;



public enum VerminGradingScale  {
    VB((short)0),
    V0((short)1),
    V1((short)2),
    V2((short)3),
    V3((short)4),
    V4((short)5),
    V5((short)6),
    V6((short)7),
    V7((short)8),
    V8((short)9),
    V9((short)10),
    V10((short)11),
    V11((short)12),
    V12((short)13),
    V13((short)14),
    V14((short)15),
    V15((short)16),
    V16((short)17),
    V17((short)18),
    INVALID((short)255);

    protected short value;

    private VerminGradingScale(short value) {
        this.value = value;
    }

    public static VerminGradingScale getByValue(final Short value) {
        for (final VerminGradingScale type : VerminGradingScale.values()) {
            if (value == type.value)
                return type;
        }

        return VerminGradingScale.INVALID;
    }

    /**
     * Retrieves the String Representation of the Value
     * @param value The enum constant
     * @return The name of this enum constant
     */
    public static String getStringFromValue( VerminGradingScale value ) {
        return value.name();
    }

    public short getValue() {
        return value;
    }


}
