/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2023 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.120Release
// Tag = production/release/21.120.00-0-g2d77811
/////////////////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;



public class StressLevelMesg extends Mesg   {

    
    public static final int StressLevelValueFieldNum = 0;
    
    public static final int StressLevelTimeFieldNum = 1;
    

    protected static final  Mesg stressLevelMesg;
    static {
        // stress_level
        stressLevelMesg = new Mesg("stress_level", MesgNum.STRESS_LEVEL);
        stressLevelMesg.addField(new Field("stress_level_value", StressLevelValueFieldNum, 131, 1, 0, "", false, Profile.Type.SINT16));
        
        stressLevelMesg.addField(new Field("stress_level_time", StressLevelTimeFieldNum, 134, 1, 0, "s", false, Profile.Type.DATE_TIME));
        
    }

    public StressLevelMesg() {
        super(Factory.createMesg(MesgNum.STRESS_LEVEL));
    }

    public StressLevelMesg(final Mesg mesg) {
        super(mesg);
    }


    /**
     * Get stress_level_value field
     *
     * @return stress_level_value
     */
    public Short getStressLevelValue() {
        return getFieldShortValue(0, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD);
    }

    /**
     * Set stress_level_value field
     *
     * @param stressLevelValue The new stressLevelValue value to be set
     */
    public void setStressLevelValue(Short stressLevelValue) {
        setFieldValue(0, 0, stressLevelValue, Fit.SUBFIELD_INDEX_MAIN_FIELD);
    }

    /**
     * Get stress_level_time field
     * Units: s
     * Comment: Time stress score was calculated
     *
     * @return stress_level_time
     */
    public DateTime getStressLevelTime() {
        return timestampToDateTime(getFieldLongValue(1, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD));
    }

    /**
     * Set stress_level_time field
     * Units: s
     * Comment: Time stress score was calculated
     *
     * @param stressLevelTime The new stressLevelTime value to be set
     */
    public void setStressLevelTime(DateTime stressLevelTime) {
        setFieldValue(1, 0, stressLevelTime.getTimestamp(), Fit.SUBFIELD_INDEX_MAIN_FIELD);
    }

}
