/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2024 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.158.0Release
// Tag = production/release/21.158.0-0-gc9428aa
/////////////////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;


public enum AutolapTrigger  {
    TIME((short)0),
    DISTANCE((short)1),
    POSITION_START((short)2),
    POSITION_LAP((short)3),
    POSITION_WAYPOINT((short)4),
    POSITION_MARKED((short)5),
    OFF((short)6),
    AUTO_SELECT((short)13),
    INVALID((short)255);

    protected short value;

    private AutolapTrigger(short value) {
        this.value = value;
    }

    public static AutolapTrigger getByValue(final Short value) {
        for (final AutolapTrigger type : AutolapTrigger.values()) {
            if (value == type.value)
                return type;
        }

        return AutolapTrigger.INVALID;
    }

    /**
     * Retrieves the String Representation of the Value
     * @param value The enum constant
     * @return The name of this enum constant
     */
    public static String getStringFromValue( AutolapTrigger value ) {
        return value.name();
    }

    public short getValue() {
        return value;
    }


}
