/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.188.0Release
// Tag = production/release/21.188.0-0-g55050f8
/////////////////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;

public enum Bool {
    FALSE((short)0),
    TRUE((short)1),
    INVALID((short)255);

    protected short value;

    private Bool(short value) {
        this.value = value;
    }

    protected static Bool getByValue(final Short value) {
        for (final Bool type : Bool.values()) {
            if (value == type.value)
                return type;
        }

        return Bool.INVALID;
    }

    public short getValue() {
        return value;
    }
}
