/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2024 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.158.0Release
// Tag = production/release/21.158.0-0-gc9428aa
/////////////////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;


public enum CameraOrientationType  {
    CAMERA_ORIENTATION_0((short)0),
    CAMERA_ORIENTATION_90((short)1),
    CAMERA_ORIENTATION_180((short)2),
    CAMERA_ORIENTATION_270((short)3),
    INVALID((short)255);

    protected short value;

    private CameraOrientationType(short value) {
        this.value = value;
    }

    public static CameraOrientationType getByValue(final Short value) {
        for (final CameraOrientationType type : CameraOrientationType.values()) {
            if (value == type.value)
                return type;
        }

        return CameraOrientationType.INVALID;
    }

    /**
     * Retrieves the String Representation of the Value
     * @param value The enum constant
     * @return The name of this enum constant
     */
    public static String getStringFromValue( CameraOrientationType value ) {
        return value.name();
    }

    public short getValue() {
        return value;
    }


}
