/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.171.0Release
// Tag = production/release/21.171.0-0-g57fed75
/////////////////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;

import java.util.HashMap;
import java.util.Map;

public class CarryExerciseName  {
    public static final int BAR_HOLDS = 0;
    public static final int FARMERS_WALK = 1;
    public static final int FARMERS_WALK_ON_TOES = 2;
    public static final int HEX_DUMBBELL_HOLD = 3;
    public static final int OVERHEAD_CARRY = 4;
    public static final int DUMBBELL_WAITER_CARRY = 5;
    public static final int FARMERS_CARRY_WALK_LUNGE = 6;
    public static final int FARMERS_CARRY = 7;
    public static final int FARMERS_CARRY_ON_TOES = 8;
    public static final int INVALID = Fit.UINT16_INVALID;

    private static final Map<Integer, String> stringMap;

    static {
        stringMap = new HashMap<Integer, String>();
        stringMap.put(BAR_HOLDS, "BAR_HOLDS");
        stringMap.put(FARMERS_WALK, "FARMERS_WALK");
        stringMap.put(FARMERS_WALK_ON_TOES, "FARMERS_WALK_ON_TOES");
        stringMap.put(HEX_DUMBBELL_HOLD, "HEX_DUMBBELL_HOLD");
        stringMap.put(OVERHEAD_CARRY, "OVERHEAD_CARRY");
        stringMap.put(DUMBBELL_WAITER_CARRY, "DUMBBELL_WAITER_CARRY");
        stringMap.put(FARMERS_CARRY_WALK_LUNGE, "FARMERS_CARRY_WALK_LUNGE");
        stringMap.put(FARMERS_CARRY, "FARMERS_CARRY");
        stringMap.put(FARMERS_CARRY_ON_TOES, "FARMERS_CARRY_ON_TOES");
    }


    /**
     * Retrieves the String Representation of the Value
     * @param value The enum constant
     * @return The name of this enum contsant
     */
    public static String getStringFromValue( Integer value ) {
        if( stringMap.containsKey( value ) ) {
            return stringMap.get( value );
        }

        return "";
    }

    /**
     * Returns the enum constant with the specified name.
     * @param value The enum string value
     * @return The enum constant or INVALID if unknown
     */
    public static Integer getValueFromString( String value ) {
        for( Map.Entry<Integer, String> entry : stringMap.entrySet() ) {
            if( entry.getValue().equals( value ) ) {
                return entry.getKey();
            }
        }

        return INVALID;
    }

}
