/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.171.0Release
// Tag = production/release/21.171.0-0-g57fed75
/////////////////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;


public enum DisplayMeasure  {
    METRIC((short)0),
    STATUTE((short)1),
    NAUTICAL((short)2),
    INVALID((short)255);

    protected short value;

    private DisplayMeasure(short value) {
        this.value = value;
    }

    public static DisplayMeasure getByValue(final Short value) {
        for (final DisplayMeasure type : DisplayMeasure.values()) {
            if (value == type.value)
                return type;
        }

        return DisplayMeasure.INVALID;
    }

    /**
     * Retrieves the String Representation of the Value
     * @param value The enum constant
     * @return The name of this enum constant
     */
    public static String getStringFromValue( DisplayMeasure value ) {
        return value.name();
    }

    public short getValue() {
        return value;
    }


}
