/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2024 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.141.0Release
// Tag = production/release/21.141.0-0-g2aa27e1
/////////////////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;


public enum GasConsumptionRateType  {
    PRESSURE_SAC((short)0),
    VOLUME_SAC((short)1),
    RMV((short)2),
    INVALID((short)255);

    protected short value;

    private GasConsumptionRateType(short value) {
        this.value = value;
    }

    public static GasConsumptionRateType getByValue(final Short value) {
        for (final GasConsumptionRateType type : GasConsumptionRateType.values()) {
            if (value == type.value)
                return type;
        }

        return GasConsumptionRateType.INVALID;
    }

    /**
     * Retrieves the String Representation of the Value
     * @param value The enum constant
     * @return The name of this enum constant
     */
    public static String getStringFromValue( GasConsumptionRateType value ) {
        return value.name();
    }

    public short getValue() {
        return value;
    }


}
