/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2024 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.135.0Release
// Tag = production/release/21.135.0-0-gb1437fb
/////////////////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;



public class HsaStepDataMesg extends Mesg   {

    
    public static final int TimestampFieldNum = 253;
    
    public static final int ProcessingIntervalFieldNum = 0;
    
    public static final int StepsFieldNum = 1;
    

    protected static final  Mesg hsaStepDataMesg;
    static {
        // hsa_step_data
        hsaStepDataMesg = new Mesg("hsa_step_data", MesgNum.HSA_STEP_DATA);
        hsaStepDataMesg.addField(new Field("timestamp", TimestampFieldNum, 134, 1, 0, "s", false, Profile.Type.DATE_TIME));
        
        hsaStepDataMesg.addField(new Field("processing_interval", ProcessingIntervalFieldNum, 132, 1, 0, "s", false, Profile.Type.UINT16));
        
        hsaStepDataMesg.addField(new Field("steps", StepsFieldNum, 134, 1, 0, "steps", false, Profile.Type.UINT32));
        
    }

    public HsaStepDataMesg() {
        super(Factory.createMesg(MesgNum.HSA_STEP_DATA));
    }

    public HsaStepDataMesg(final Mesg mesg) {
        super(mesg);
    }


    /**
     * Get timestamp field
     * Units: s
     *
     * @return timestamp
     */
    public DateTime getTimestamp() {
        return timestampToDateTime(getFieldLongValue(253, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD));
    }

    /**
     * Set timestamp field
     * Units: s
     *
     * @param timestamp The new timestamp value to be set
     */
    public void setTimestamp(DateTime timestamp) {
        setFieldValue(253, 0, timestamp.getTimestamp(), Fit.SUBFIELD_INDEX_MAIN_FIELD);
    }

    /**
     * Get processing_interval field
     * Units: s
     * Comment: Processing interval length in seconds
     *
     * @return processing_interval
     */
    public Integer getProcessingInterval() {
        return getFieldIntegerValue(0, 0, Fit.SUBFIELD_INDEX_MAIN_FIELD);
    }

    /**
     * Set processing_interval field
     * Units: s
     * Comment: Processing interval length in seconds
     *
     * @param processingInterval The new processingInterval value to be set
     */
    public void setProcessingInterval(Integer processingInterval) {
        setFieldValue(0, 0, processingInterval, Fit.SUBFIELD_INDEX_MAIN_FIELD);
    }

    public Long[] getSteps() {
        
        return getFieldLongValues(1, Fit.SUBFIELD_INDEX_MAIN_FIELD);
        
    }

    /**
     * @return number of steps
     */
    public int getNumSteps() {
        return getNumFieldValues(1, Fit.SUBFIELD_INDEX_MAIN_FIELD);
    }

    /**
     * Get steps field
     * Units: steps
     * Comment: Total step sum
     *
     * @param index of steps
     * @return steps
     */
    public Long getSteps(int index) {
        return getFieldLongValue(1, index, Fit.SUBFIELD_INDEX_MAIN_FIELD);
    }

    /**
     * Set steps field
     * Units: steps
     * Comment: Total step sum
     *
     * @param index of steps
     * @param steps The new steps value to be set
     */
    public void setSteps(int index, Long steps) {
        setFieldValue(1, index, steps, Fit.SUBFIELD_INDEX_MAIN_FIELD);
    }

}
