/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.188.0Release
// Tag = production/release/21.188.0-0-g55050f8
/////////////////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;

public interface MesgWithEvent {
    public DateTime getTimestamp();
    public void setTimestamp(DateTime timestamp);
    public Event getEvent();
    public void setEvent(Event event);
    public EventType getEventType();
    public void setEventType(EventType type);
    public Short getEventGroup();
    public void setEventGroup(Short group);
}
