/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.176.0Release
// Tag = production/release/21.176.0-0-ga30c8ed
/////////////////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;


public enum ProjectileType  {
    ARROW((short)0),
    RIFLE_CARTRIDGE((short)1),
    PISTOL_CARTRIDGE((short)2),
    SHOTSHELL((short)3),
    AIR_RIFLE_PELLET((short)4),
    OTHER((short)5),
    INVALID((short)255);

    protected short value;

    private ProjectileType(short value) {
        this.value = value;
    }

    public static ProjectileType getByValue(final Short value) {
        for (final ProjectileType type : ProjectileType.values()) {
            if (value == type.value)
                return type;
        }

        return ProjectileType.INVALID;
    }

    /**
     * Retrieves the String Representation of the Value
     * @param value The enum constant
     * @return The name of this enum constant
     */
    public static String getStringFromValue( ProjectileType value ) {
        return value.name();
    }

    public short getValue() {
        return value;
    }


}
