/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.188.0Release
// Tag = production/release/21.188.0-0-g55050f8
/////////////////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;

import java.util.HashMap;
import java.util.Map;

public class SportBits1  {
    public static final short TENNIS = 0x01;
    public static final short AMERICAN_FOOTBALL = 0x02;
    public static final short TRAINING = 0x04;
    public static final short WALKING = 0x08;
    public static final short CROSS_COUNTRY_SKIING = 0x10;
    public static final short ALPINE_SKIING = 0x20;
    public static final short SNOWBOARDING = 0x40;
    public static final short ROWING = 0x80;
    public static final short INVALID = Fit.UINT8Z_INVALID;

    private static final Map<Short, String> stringMap;

    static {
        stringMap = new HashMap<Short, String>();
        stringMap.put(TENNIS, "TENNIS");
        stringMap.put(AMERICAN_FOOTBALL, "AMERICAN_FOOTBALL");
        stringMap.put(TRAINING, "TRAINING");
        stringMap.put(WALKING, "WALKING");
        stringMap.put(CROSS_COUNTRY_SKIING, "CROSS_COUNTRY_SKIING");
        stringMap.put(ALPINE_SKIING, "ALPINE_SKIING");
        stringMap.put(SNOWBOARDING, "SNOWBOARDING");
        stringMap.put(ROWING, "ROWING");
    }


    /**
     * Retrieves the String Representation of the Value
     * @param value The enum constant
     * @return The name of this enum contsant
     */
    public static String getStringFromValue( Short value ) {
        if( stringMap.containsKey( value ) ) {
            return stringMap.get( value );
        }

        return "";
    }

    /**
     * Returns the enum constant with the specified name.
     * @param value The enum string value
     * @return The enum constant or INVALID if unknown
     */
    public static Short getValueFromString( String value ) {
        for( Map.Entry<Short, String> entry : stringMap.entrySet() ) {
            if( entry.getValue().equals( value ) ) {
                return entry.getKey();
            }
        }

        return INVALID;
    }

}
