/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.171.0Release
// Tag = production/release/21.171.0-0-g57fed75
/////////////////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;

import java.util.HashMap;
import java.util.Map;

public class WarmUpExerciseName  {
    public static final int QUADRUPED_ROCKING = 0;
    public static final int NECK_TILTS = 1;
    public static final int ANKLE_CIRCLES = 2;
    public static final int ANKLE_DORSIFLEXION_WITH_BAND = 3;
    public static final int ANKLE_INTERNAL_ROTATION = 4;
    public static final int ARM_CIRCLES = 5;
    public static final int BENT_OVER_REACH_TO_SKY = 6;
    public static final int CAT_CAMEL = 7;
    public static final int ELBOW_TO_FOOT_LUNGE = 8;
    public static final int FORWARD_AND_BACKWARD_LEG_SWINGS = 9;
    public static final int GROINERS = 10;
    public static final int INVERTED_HAMSTRING_STRETCH = 11;
    public static final int LATERAL_DUCK_UNDER = 12;
    public static final int NECK_ROTATIONS = 13;
    public static final int OPPOSITE_ARM_AND_LEG_BALANCE = 14;
    public static final int REACH_ROLL_AND_LIFT = 15;
    public static final int SCORPION = 16; // Deprecated do not use
    public static final int SHOULDER_CIRCLES = 17;
    public static final int SIDE_TO_SIDE_LEG_SWINGS = 18;
    public static final int SLEEPER_STRETCH = 19;
    public static final int SLIDE_OUT = 20;
    public static final int SWISS_BALL_HIP_CROSSOVER = 21;
    public static final int SWISS_BALL_REACH_ROLL_AND_LIFT = 22;
    public static final int SWISS_BALL_WINDSHIELD_WIPERS = 23;
    public static final int THORACIC_ROTATION = 24;
    public static final int WALKING_HIGH_KICKS = 25;
    public static final int WALKING_HIGH_KNEES = 26;
    public static final int WALKING_KNEE_HUGS = 27;
    public static final int WALKING_LEG_CRADLES = 28;
    public static final int WALKOUT = 29;
    public static final int WALKOUT_FROM_PUSH_UP_POSITION = 30;
    public static final int BICEPS_STRETCH = 31;
    public static final int GLUTES_STRETCH = 32;
    public static final int STANDING_HAMSTRING_STRETCH = 33;
    public static final int STRETCH_90_90 = 34;
    public static final int STRETCH_ABS = 35;
    public static final int STRETCH_BUTTERFLY = 36;
    public static final int STRETCH_CALF = 37;
    public static final int STRETCH_CAT_COW = 38;
    public static final int STRETCH_CHILDS_POSE = 39;
    public static final int STRETCH_COBRA = 40;
    public static final int STRETCH_FOREARMS = 41;
    public static final int STRETCH_FORWARD_GLUTES = 42;
    public static final int STRETCH_FRONT_SPLIT = 43;
    public static final int STRETCH_HAMSTRING = 44;
    public static final int STRETCH_HIP_FLEXOR_AND_QUAD = 45;
    public static final int STRETCH_LAT = 46;
    public static final int STRETCH_LEVATOR_SCAPULAE = 47;
    public static final int STRETCH_LUNGE_WITH_SPINAL_TWIST = 48;
    public static final int STRETCH_LUNGING_HIP_FLEXOR = 49;
    public static final int STRETCH_LYING_ABDUCTION = 50;
    public static final int STRETCH_LYING_IT_BAND = 51;
    public static final int STRETCH_LYING_KNEE_TO_CHEST = 52;
    public static final int STRETCH_LYING_PIRIFORMIS = 53;
    public static final int STRETCH_LYING_SPINAL_TWIST = 54;
    public static final int STRETCH_NECK = 55;
    public static final int STRETCH_OBLIQUES = 56;
    public static final int STRETCH_OVER_UNDER_SHOULDER = 57;
    public static final int STRETCH_PECTORAL = 58;
    public static final int STRETCH_PIGEON_POSE = 59;
    public static final int STRETCH_PIRIFORMIS = 60;
    public static final int STRETCH_QUAD = 61;
    public static final int STRETCH_SCORPION = 62;
    public static final int STRETCH_SHOULDER = 63;
    public static final int STRETCH_SIDE = 64;
    public static final int STRETCH_SIDE_LUNGE = 65;
    public static final int STRETCH_SIDE_SPLIT = 66;
    public static final int STRETCH_STANDING_IT_BAND = 67;
    public static final int STRETCH_STRADDLE = 68;
    public static final int STRETCH_TRICEPS = 69;
    public static final int STRETCH_WALL_CHEST_AND_SHOULDER = 70;
    public static final int NECK_ROTATIONS_WHEELCHAIR = 71;
    public static final int HALF_KNEELING_ARM_ROTATION = 72;
    public static final int THREE_WAY_ANKLE_MOBILIZATION = 73;
    public static final int NINETY_NINETY_HIP_SWITCH = 74; // 90_90_hip_switch
    public static final int ACTIVE_FROG = 75;
    public static final int SHOULDER_SWEEPS = 76;
    public static final int ANKLE_LUNGES = 77;
    public static final int BACK_ROLL_FOAM_ROLLER = 78;
    public static final int BEAR_CRAWL = 79;
    public static final int LATISSIMUS_DORSI_FOAM_ROLL = 80;
    public static final int REVERSE_T_HIP_OPENER = 81;
    public static final int SHOULDER_ROLLS = 82;
    public static final int CHEST_OPENERS = 83;
    public static final int TRICEPS_STRETCH = 84;
    public static final int UPPER_BACK_STRETCH = 85;
    public static final int HIP_CIRCLES = 86;
    public static final int ANKLE_STRETCH = 87;
    public static final int MARCHING_IN_PLACE = 88;
    public static final int TRICEPS_STRETCH_WHEELCHAIR = 89;
    public static final int UPPER_BACK_STRETCH_WHEELCHAIR = 90;
    public static final int INVALID = Fit.UINT16_INVALID;

    private static final Map<Integer, String> stringMap;

    static {
        stringMap = new HashMap<Integer, String>();
        stringMap.put(QUADRUPED_ROCKING, "QUADRUPED_ROCKING");
        stringMap.put(NECK_TILTS, "NECK_TILTS");
        stringMap.put(ANKLE_CIRCLES, "ANKLE_CIRCLES");
        stringMap.put(ANKLE_DORSIFLEXION_WITH_BAND, "ANKLE_DORSIFLEXION_WITH_BAND");
        stringMap.put(ANKLE_INTERNAL_ROTATION, "ANKLE_INTERNAL_ROTATION");
        stringMap.put(ARM_CIRCLES, "ARM_CIRCLES");
        stringMap.put(BENT_OVER_REACH_TO_SKY, "BENT_OVER_REACH_TO_SKY");
        stringMap.put(CAT_CAMEL, "CAT_CAMEL");
        stringMap.put(ELBOW_TO_FOOT_LUNGE, "ELBOW_TO_FOOT_LUNGE");
        stringMap.put(FORWARD_AND_BACKWARD_LEG_SWINGS, "FORWARD_AND_BACKWARD_LEG_SWINGS");
        stringMap.put(GROINERS, "GROINERS");
        stringMap.put(INVERTED_HAMSTRING_STRETCH, "INVERTED_HAMSTRING_STRETCH");
        stringMap.put(LATERAL_DUCK_UNDER, "LATERAL_DUCK_UNDER");
        stringMap.put(NECK_ROTATIONS, "NECK_ROTATIONS");
        stringMap.put(OPPOSITE_ARM_AND_LEG_BALANCE, "OPPOSITE_ARM_AND_LEG_BALANCE");
        stringMap.put(REACH_ROLL_AND_LIFT, "REACH_ROLL_AND_LIFT");
        stringMap.put(SCORPION, "SCORPION");
        stringMap.put(SHOULDER_CIRCLES, "SHOULDER_CIRCLES");
        stringMap.put(SIDE_TO_SIDE_LEG_SWINGS, "SIDE_TO_SIDE_LEG_SWINGS");
        stringMap.put(SLEEPER_STRETCH, "SLEEPER_STRETCH");
        stringMap.put(SLIDE_OUT, "SLIDE_OUT");
        stringMap.put(SWISS_BALL_HIP_CROSSOVER, "SWISS_BALL_HIP_CROSSOVER");
        stringMap.put(SWISS_BALL_REACH_ROLL_AND_LIFT, "SWISS_BALL_REACH_ROLL_AND_LIFT");
        stringMap.put(SWISS_BALL_WINDSHIELD_WIPERS, "SWISS_BALL_WINDSHIELD_WIPERS");
        stringMap.put(THORACIC_ROTATION, "THORACIC_ROTATION");
        stringMap.put(WALKING_HIGH_KICKS, "WALKING_HIGH_KICKS");
        stringMap.put(WALKING_HIGH_KNEES, "WALKING_HIGH_KNEES");
        stringMap.put(WALKING_KNEE_HUGS, "WALKING_KNEE_HUGS");
        stringMap.put(WALKING_LEG_CRADLES, "WALKING_LEG_CRADLES");
        stringMap.put(WALKOUT, "WALKOUT");
        stringMap.put(WALKOUT_FROM_PUSH_UP_POSITION, "WALKOUT_FROM_PUSH_UP_POSITION");
        stringMap.put(BICEPS_STRETCH, "BICEPS_STRETCH");
        stringMap.put(GLUTES_STRETCH, "GLUTES_STRETCH");
        stringMap.put(STANDING_HAMSTRING_STRETCH, "STANDING_HAMSTRING_STRETCH");
        stringMap.put(STRETCH_90_90, "STRETCH_90_90");
        stringMap.put(STRETCH_ABS, "STRETCH_ABS");
        stringMap.put(STRETCH_BUTTERFLY, "STRETCH_BUTTERFLY");
        stringMap.put(STRETCH_CALF, "STRETCH_CALF");
        stringMap.put(STRETCH_CAT_COW, "STRETCH_CAT_COW");
        stringMap.put(STRETCH_CHILDS_POSE, "STRETCH_CHILDS_POSE");
        stringMap.put(STRETCH_COBRA, "STRETCH_COBRA");
        stringMap.put(STRETCH_FOREARMS, "STRETCH_FOREARMS");
        stringMap.put(STRETCH_FORWARD_GLUTES, "STRETCH_FORWARD_GLUTES");
        stringMap.put(STRETCH_FRONT_SPLIT, "STRETCH_FRONT_SPLIT");
        stringMap.put(STRETCH_HAMSTRING, "STRETCH_HAMSTRING");
        stringMap.put(STRETCH_HIP_FLEXOR_AND_QUAD, "STRETCH_HIP_FLEXOR_AND_QUAD");
        stringMap.put(STRETCH_LAT, "STRETCH_LAT");
        stringMap.put(STRETCH_LEVATOR_SCAPULAE, "STRETCH_LEVATOR_SCAPULAE");
        stringMap.put(STRETCH_LUNGE_WITH_SPINAL_TWIST, "STRETCH_LUNGE_WITH_SPINAL_TWIST");
        stringMap.put(STRETCH_LUNGING_HIP_FLEXOR, "STRETCH_LUNGING_HIP_FLEXOR");
        stringMap.put(STRETCH_LYING_ABDUCTION, "STRETCH_LYING_ABDUCTION");
        stringMap.put(STRETCH_LYING_IT_BAND, "STRETCH_LYING_IT_BAND");
        stringMap.put(STRETCH_LYING_KNEE_TO_CHEST, "STRETCH_LYING_KNEE_TO_CHEST");
        stringMap.put(STRETCH_LYING_PIRIFORMIS, "STRETCH_LYING_PIRIFORMIS");
        stringMap.put(STRETCH_LYING_SPINAL_TWIST, "STRETCH_LYING_SPINAL_TWIST");
        stringMap.put(STRETCH_NECK, "STRETCH_NECK");
        stringMap.put(STRETCH_OBLIQUES, "STRETCH_OBLIQUES");
        stringMap.put(STRETCH_OVER_UNDER_SHOULDER, "STRETCH_OVER_UNDER_SHOULDER");
        stringMap.put(STRETCH_PECTORAL, "STRETCH_PECTORAL");
        stringMap.put(STRETCH_PIGEON_POSE, "STRETCH_PIGEON_POSE");
        stringMap.put(STRETCH_PIRIFORMIS, "STRETCH_PIRIFORMIS");
        stringMap.put(STRETCH_QUAD, "STRETCH_QUAD");
        stringMap.put(STRETCH_SCORPION, "STRETCH_SCORPION");
        stringMap.put(STRETCH_SHOULDER, "STRETCH_SHOULDER");
        stringMap.put(STRETCH_SIDE, "STRETCH_SIDE");
        stringMap.put(STRETCH_SIDE_LUNGE, "STRETCH_SIDE_LUNGE");
        stringMap.put(STRETCH_SIDE_SPLIT, "STRETCH_SIDE_SPLIT");
        stringMap.put(STRETCH_STANDING_IT_BAND, "STRETCH_STANDING_IT_BAND");
        stringMap.put(STRETCH_STRADDLE, "STRETCH_STRADDLE");
        stringMap.put(STRETCH_TRICEPS, "STRETCH_TRICEPS");
        stringMap.put(STRETCH_WALL_CHEST_AND_SHOULDER, "STRETCH_WALL_CHEST_AND_SHOULDER");
        stringMap.put(NECK_ROTATIONS_WHEELCHAIR, "NECK_ROTATIONS_WHEELCHAIR");
        stringMap.put(HALF_KNEELING_ARM_ROTATION, "HALF_KNEELING_ARM_ROTATION");
        stringMap.put(THREE_WAY_ANKLE_MOBILIZATION, "THREE_WAY_ANKLE_MOBILIZATION");
        stringMap.put(NINETY_NINETY_HIP_SWITCH, "NINETY_NINETY_HIP_SWITCH");
        stringMap.put(ACTIVE_FROG, "ACTIVE_FROG");
        stringMap.put(SHOULDER_SWEEPS, "SHOULDER_SWEEPS");
        stringMap.put(ANKLE_LUNGES, "ANKLE_LUNGES");
        stringMap.put(BACK_ROLL_FOAM_ROLLER, "BACK_ROLL_FOAM_ROLLER");
        stringMap.put(BEAR_CRAWL, "BEAR_CRAWL");
        stringMap.put(LATISSIMUS_DORSI_FOAM_ROLL, "LATISSIMUS_DORSI_FOAM_ROLL");
        stringMap.put(REVERSE_T_HIP_OPENER, "REVERSE_T_HIP_OPENER");
        stringMap.put(SHOULDER_ROLLS, "SHOULDER_ROLLS");
        stringMap.put(CHEST_OPENERS, "CHEST_OPENERS");
        stringMap.put(TRICEPS_STRETCH, "TRICEPS_STRETCH");
        stringMap.put(UPPER_BACK_STRETCH, "UPPER_BACK_STRETCH");
        stringMap.put(HIP_CIRCLES, "HIP_CIRCLES");
        stringMap.put(ANKLE_STRETCH, "ANKLE_STRETCH");
        stringMap.put(MARCHING_IN_PLACE, "MARCHING_IN_PLACE");
        stringMap.put(TRICEPS_STRETCH_WHEELCHAIR, "TRICEPS_STRETCH_WHEELCHAIR");
        stringMap.put(UPPER_BACK_STRETCH_WHEELCHAIR, "UPPER_BACK_STRETCH_WHEELCHAIR");
    }


    /**
     * Retrieves the String Representation of the Value
     * @param value The enum constant
     * @return The name of this enum contsant
     */
    public static String getStringFromValue( Integer value ) {
        if( stringMap.containsKey( value ) ) {
            return stringMap.get( value );
        }

        return "";
    }

    /**
     * Returns the enum constant with the specified name.
     * @param value The enum string value
     * @return The enum constant or INVALID if unknown
     */
    public static Integer getValueFromString( String value ) {
        for( Map.Entry<Integer, String> entry : stringMap.entrySet() ) {
            if( entry.getValue().equals( value ) ) {
                return entry.getKey();
            }
        }

        return INVALID;
    }

}
