/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2024 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.158.0Release
// Tag = production/release/21.158.0-0-gc9428aa
/////////////////////////////////////////////////////////////////////////////////////////////


package com.garmin.fit;


public enum WorkoutEquipment  {
    NONE((short)0),
    SWIM_FINS((short)1),
    SWIM_KICKBOARD((short)2),
    SWIM_PADDLES((short)3),
    SWIM_PULL_BUOY((short)4),
    SWIM_SNORKEL((short)5),
    INVALID((short)255);

    protected short value;

    private WorkoutEquipment(short value) {
        this.value = value;
    }

    public static WorkoutEquipment getByValue(final Short value) {
        for (final WorkoutEquipment type : WorkoutEquipment.values()) {
            if (value == type.value)
                return type;
        }

        return WorkoutEquipment.INVALID;
    }

    /**
     * Retrieves the String Representation of the Value
     * @param value The enum constant
     * @return The name of this enum constant
     */
    public static String getStringFromValue( WorkoutEquipment value ) {
        return value.name();
    }

    public short getValue() {
        return value;
    }


}
